common/content.go, common/content_test.go, common/go.mod, common/go.sum, storage/NOTES.md, storage/README.markdown
JSON serializable structures for storage and exchange of content.
Closes: #6
=> data structures

storage/go.mod, storage/go.sum, storage/storage.go, storage/storage_test.go
=> Update Node#IsPartOf when applying results

lambdas/transform-parsoid/Makefile, lambdas/transform-parsoid/main.go
Implements loading linked data from s3 raw storage and adds it to canonical format
Closes #23
=> Load "About" from s3 raw storage

env/config.mk, lambdas/transform-parsoid/Makefile
=> Pass '$(PHX_S3_STRUCTURED_CONTENT_BUCKET) to transform-pasoid lambda

storage/README.markdown, storage/go.mod, storage/go.sum, storage/indexing.go, storage/indexing_test.go, storage/page_name_mapping.json, storage/storage.go, storage/storage_test.go
A work-in-progress.
Closes #13, and closes #5
=> By-name indexing of Page objects

lambdas/transform-parsoid/nodeParser.go
=> Pass dateModified from page to related node

README.markdown
Adds overview description to the ReadMe file
=> Publish pov readme

demo/README.md
Add forgotten instructions in the README on how to deploy the demo UI.
=> Add instructions to deploy the UI

demo/public/sandbox/index.html, demo/src/App.vue
Standalone GraphiQL interface that allows testing the GraphQL queries with our schema.
Fixes #66
=> Add GraphiQL sandbox

demo/public/sandbox/index.html, demo/src/App.vue
Make the URL go back to the general demo in both localhost
and the github.io page.
=> Quickfix URL in sandbox

demo/rosette/.gitignore, demo/rosette/README.md, demo/rosette/config.sample.js, demo/rosette/index.js, demo/rosette/package-lock.json, demo/rosette/package.json
This is a quick script to check into the response from several
Rosette.com endpoints with given sections.
Related to #49
=> Rosette experiment

docs/artifact.md
Draft to share for feedback and for other's to add stuff
=> Artifact draft

docs/artifact.md
"Final" changes from Diana. Others add as desired.
=> Artifact final

demo/public/sandbox/index.html, demo/src/components/FormFetchPageSctions.vue
Update demo to point to the aws endpoint so the github pages works.
=> Change GraphQL endpoint from localhost to aws

demo/package-lock.json, demo/package.json, demo/src/App.vue, demo/src/components/FormFetchKeyword.vue, demo/src/components/SectionBox.vue, demo/src/components/SectionCollection.vue, demo/src/main.js, demo/src/router/index.js, demo/src/views/FetchKeyword.vue
Demo page added "Fetch sections by keyword" with a preliminary
list of Wikidata items with some section results.
=> Add demo for fetching sections by Wikidata keyword

service/schema.gql, service/service.go
=> service: rename `relatedTo` arg to `keyword`

demo/package.json, demo/public/sandbox/index.html, demo/src/components/FormFetchKeyword.vue, demo/src/components/SectionBox.vue, demo/src/components/SectionCollection.vue
1. Change 'relatedTo' to 'keyword'
2. (initial) fix for isPartOf as an object rather than an ID
3. Create a proper way to test local vs deployment with option
for testing local graphql.
=> Followup graphql changes in the demo interface

demo/netlify.toml
See: https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps
=> Fix SPA routing rules in Netlify

demo/package-lock.json, demo/package.json, demo/src/components/FormFetchKeyword.vue, demo/src/components/FormFetchPageSctions.vue, demo/src/components/PageInfo.vue, demo/src/components/SectionBox.vue, demo/src/components/SectionCollection.vue, demo/src/components/TitleAutocomplete.vue
* Add ID to the fetch from GraphQL so we can clean up dupes
* Clean up / normalize display title and display section name
* Add dialog for full page view, add button to open it from sections
* Add TitleAutocomplete that fetches title search suggestions
from Simple English wikipedia (added to fetch part of a page)
Fixes #105
=> Interface fixes

demo/public/sandbox/index.html, demo/src/App.vue
=> Add "prototype" banner

demo/public/index.html, demo/src/components/SectionBox.vue
- Add proper <title>
- Make sure section titles in SectionBox wrap on words
- "Stick" the salience bubble to the right
=> Formatting fixes for the demo
